EventDB/EventApp/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventApp.Data;
using EventApp.Models;

namespace EventApp.Controllers
{
    public class CartsController : Controller
    {
        private EventAppContext db = new EventAppContext();

        // GET: Carts
        public ActionResult Index()
        {
            return View(db.Carts.ToList());
        }

        // GET: Carts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Carts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecordId,CartId,OrderId,DateCreated,EventId,Count")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cart);
        }

        // GET: Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RecordId,CartId,OrderId,DateCreated,EventId,Count")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cart cart = db.Carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cart cart = db.Carts.Find(id);
            db.Carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventDB/EventApp/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventApp.Data;
using EventApplication.Models;

namespace EventApp.Controllers
{
    public class EventsController : Controller
    {
        private EventAppContext db = new EventAppContext();


        public ActionResult EventSearch(string q)
        {

            var events = db.Events;
            return PartialView("_Eventsearch", events);

        }
        private List<Events> GetEvents(string searchString)
        {
            return db.Events
                    .Where(a => a.EventTitle.Contains(searchString))
                    .ToList();
        }
        public ActionResult GetState(string v)
        {
            var states = GetState(v);
            return PartialView("_StateSearch", states);

        }










            // GET: Events
            public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventsId,EventTitle,EventDescription,EventStartTime,EventStartDate,EventEndTime,EventEndDate,City,State,EventType,OrganizerName,OrganizerContactInfo,MaxTickets,AvaliableTickets")] Events events)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(events);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(events);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventsId,EventTitle,EventDescription,EventStartTime,EventStartDate,EventEndTime,EventEndDate,City,State,EventType,OrganizerName,OrganizerContactInfo,MaxTickets,AvaliableTickets")] Events events)
        {
            if (ModelState.IsValid)
            {
                db.Entry(events).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(events);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Events events = db.Events.Find(id);
            if (events == null)
            {
                return HttpNotFound();
            }
            return View(events);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Events events = db.Events.Find(id);
            db.Events.Remove(events);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EventDB/EventApp/Controllers/HomeController.cs
using EventApp.Data;
using EventApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventApp.Controllers
{
    public class HomeController : Controller
    {
        private EventAppContext db = new EventAppContext();

        public ActionResult GetLastMinuteDeals()
        {
            DateTime futureDate = DateTime.Today.AddDays(2);
            var LastMinuteDeal = db.Events

            .Where(a => a.EventStartDate <= DateTime.Today)
            .Where(a => a.EventStartDate <= futureDate); 
            return PartialView  ("_LastMinuteDeals" , LastMinuteDeal);

        }

        public ActionResult EventSearch(string q)
        {

            var events = db.Events;
            return PartialView("_Eventsearch",events);

        }
      private List<Events> GetEvents(string searchString)
        {
            return db.Events
                    .Where(a => a.EventTitle.Contains(searchString))
                    .ToList();
        }
       public ActionResult GetState(string v)
        {
            var states = GetState(v);
                return PartialView("_StateSearch", states);

           


        }

        private object GetStates (string v)
        {
            return db.Events
               .Where(c => c.State.Contains(v))
                .ToList();
        }
       

        


     



        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EventDB/EventApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EventDB/EventApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EventDB/EventApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Event Unlimited</h1>
    <p class="lead">Find events near you. Never miss out again!</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class=" panel panel-default"></div>
<div class=" panel-heading"> Find an Event  </div>
<div class=" panel-body">
    @using (Ajax.BeginForm("EventSearch", "Home", new AjaxOptions

    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET",
        OnFailure = "searchFailed",
        LoadingElementId = "ajax-loader",
        UpdateTargetId = "searchresults"
    }))

    {
        <input type="text" name="q" />
        <input type="text" name="q" />
        <input type="submit" value="search" />
        <img id=" ajax-loader"
             src=" @Url.Content("~/Content/ajax-loader.gif")"
             style=" display: none" />

    }




    <div id=" Last Mintue Deal">
        @Ajax.ActionLink(" Click here to see Last Minute Deal!",
       "GetLastMinuteDeals",
       null,
       new AjaxOptions
       {
           UpdateTargetId = "lastminutedeal",
           InsertionMode = InsertionMode.Replace,
           HttpMethod = "GET"
       },
       new { @class = "btn btn-primary" })

    </div>

    <div id=" searchresults"></div>

</div>



@section Scripts {


    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

   
}

EventDB/EventApp/Views/Home/_EventSearch.cshtml
@model IEnumerable<EventApplication.Models.Events>



<<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventStartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventEndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventEndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizerContactInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxTickets)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AvaliableTickets)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventStartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventStartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventEndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizerContactInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxTickets)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvaliableTickets)
            </td>
            <td> <a href=" #" data-id="@item.EventsId ">Cancel Order</a></td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.EventsId }) |
                @Html.ActionLink("Details", "Details", new { id = item.EventsId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EventsId })
               
                @Html.ActionLink("Add to Cart", "AddToCart", "Carts",
         new { id = item.EventsId },
         new { @class = "btn btn-primary" })

            </td>
        </tr>
    }

</table>

EventDB/EventApp/Views/Home/_EventSearchResults.cshtml
@model IEnumerable<EventApplication.Models.Events>

div id=" searchresults">

<div >

    <table>
        <tr>
            <th>Event Title</th>
            <th>Edit</th>
            <th>Details</th>
            <th>Delete</th>


        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>



                    @item.EventTitle

                    </td>








                <td>

                    @Html.ActionLink("Edit", "Edit", new { id = item.EventsId })

                    </td>

                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.EventsId })
                    </td>
                <td>

                    @Html.ActionLink("Delete", "Delete", new { id = item.EventsId })
                </td>
            </tr>

        }
    </table>
</div>  

EventDB/EventApp/Views/Home/_Lastminutedeals.cshtml
@model IEnumerable<EventApplication.Models.Events>




<div>

    <table>
        <tr>
            <th>Event Title</th>
            <th>Event Start Date</th>
            <


        </tr>


        @foreach (var item in Model)
        {
            <tr>
                <td>



                    @item.EventTitle

                </td>


                <td>
                    @item.EventStartDate
                </td>





                <td>

                    @Html.ActionLink("Edit", "Edit", new { id = item.EventsId })

                </td>

                <td>
                    @Html.ActionLink("Details", "Details", "Events")
                </td>
                <td>

                    @Html.ActionLink("Delete", "Delete", new { id = item.EventsId })
                </td>
            </tr>

        }
    </table>
</div>